config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'home#home'
  resources :file_managements
  root to: 'file_managements#index'
  get 'file_download', to: 'file_managements#download'
  get 'home', to: 'file_managements#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_management.rb
class FileManagement < ApplicationRecord
	# belongs_to :user, class_name: "User", foreign_key: "user_id"
	mount_uploader :attachment, FileUploader
	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :attachment, presence: true, file_size: { less_than: 1.gigabytes }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :file_managements, class_name: "FileManagement", foreign_key: "user_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
			devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/file_managements_controller.rb
class FileManagementsController < ApplicationController
	before_action :set_file, only: [:show, :edit, :update]
 
  def index
    @files = current_user.file_managements.order('created_at ASC')
  end
 
  def show
  end
 
  def new
    @file = FileManagement.new
  end
 
  def create
    @file = FileManagement.new(file_params)
    @file.user_id = current_user.id
    if @file.save
      redirect_to file_managements_path
      flash[:alert] = "The File was successfully created."
    else
      render :new
    end
  end
 
  def edit
  end
 
  def update
    if @file.update(file_params)
      redirect_to file_managements_path(@file)
      flash[:alert] = "The File was successfully updated."
    else
      render :edit
    end
  end

  def destroy
  	@file = FileManagement.find(params[:id])
  	@file.destroy
  	flash[:notice] = "The File was successfully destroyed."
    redirect_to home_path
  end

  def download
  	@file = FileManagement.find(params[:id])
  	# byebug
  	send_file @file.attachment.url
  end
 
  private
 
  def file_params
    params.require(:file_management).permit(:title, :description, :attachment)
  end
 
  def set_file
    @file = FileManagement.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_managements_helper.rb
module FileManagementsHelper
	def url_short(url)
		client = Bitly::API::Client.new(token: 'dcc042adbb667d108d8e3c1a0e0f5fd92dc62bc1')
		bitlink = client.shorten(long_url: url)
		bitlink.link
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_managements/_file_management.html.erb
<tr>
	<td><%= file_management.title %></td>
	<td><%= file_management.description %></td>
	<td><%= file_management.attachment.file.filename %></td>
	<td><%= link_to 'Edit', edit_file_management_path(file_management) %></td>
	<td><%= link_to 'Delete', file_management, :method => 'delete' %></td>
	<td><%= link_to 'Download file', file_management.attachment.url %></td>
	<td><%= url_short("http://"+request.host.to_s+":3000"+file_management.attachment.url) %></td>
</tr>

app/views/file_managements/_form.html.erb
<%= form_for @file do |f| %>
<div>
<% if @file.errors.full_messages.any? %>
  <% @file.errors.full_messages.each do |error_message| %>
    <p style="color:red;"> <%= error_message if @file.errors.full_messages.first == error_message %></p>
  <% end %>
<% end %>  
</div>

<table>
  
  <tr>
    <td><%= f.label :title %></td>
    <td><%= f.text_field :title %></td>
  </tr>

  <tr>
    <td><%= f.label :description %></td>
    <td><%= f.text_area :description %></td>
  </tr>

  <tr>
    <td><%= f.label :attachment %></td>
    <td><%= f.file_field :attachment %></td>
  </tr>

  <tr>
    <td></td>
    <td><%= f.submit %></td>
  </tr>

</table>

<% end %>

app/views/file_managements/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form', post: @file %>

app/views/file_managements/index.html.erb
<h1>File Management</h1>
 
<%= link_to 'Add File', new_file_management_path %>
<br><hr>
 
<% if @files.present? %>
<table border="1">
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>File Name</th>
		<th></th>
		<th></th>
		<th></th>
		<th>Share this url for sharing file</th>
	</tr>
<%= render @files %>
</table> 
<% end %>

app/views/file_managements/new.html.erb
<h1>Upload Your File Here</h1>
 
<%= render 'form', post: @file %>

app/views/file_managements/show.html.erb
<%= link_to 'All Files', file_managements_path %>
<h1><%= @file.title %></h1>
 
<p><%= @file.description %></p>
 
<p><%= link_to 'Edit', edit_file_management_path(@file) %></p>

app/views/home/home.html.erb
hiiii

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filemanagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Hi <strong><%= current_user.name %></strong> you have Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <%= link_to "Home", home_path, :class => 'navbar-link'  %>
    <p style="color:red;"><%= flash[:notice] %></p>
    <p style="color:green;"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>